### ISSUE TITLE
带有功能区的地址库和京东地址库同步

### ISSUE THREAD

**Issue by PingXD** [MrZhangYuan/AddressParsing#2]
[Regions_With_Functional_Area.json.log](https://github.com/MrZhangYuan/AddressParsing/files/11269554/Regions_With_Functional_Area.json.log)

**Comment by MrZhangYuan** [comment]
好久没上github了，感谢

**Comment by Monkeywj** [comment]
> [Regions_With_Functional_Area.json.log](https://github.com/MrZhangYuan/AddressParsing/files/11269554/Regions_With_Functional_Area.json.log)

@PingXD 您好，这个数据从哪里获取到的呢。

**Comment by Monkeywj** [comment]
> [Regions_With_Functional_Area.json.log](https://github.com/MrZhangYuan/AddressParsing/files/11269554/Regions_With_Functional_Area.json.log)

@PingXD 想要一份最新的到3级的json数据，4级的太多了。

**Comment by heyblues** [comment]
> > [Regions_With_Functional_Area.json.log](https://github.com/MrZhangYuan/AddressParsing/files/11269554/Regions_With_Functional_Area.json.log)
> 
> @PingXD 您好，这个数据从哪里获取到的呢。

最新的json文件 你这个问题解决了？

**Comment by PingXD** [comment]
某东的地址库

**Comment by heyblues** [comment]
> Regions_With_Functional_Area.jso

但是这个库里面没有邮政编码，能加个qq私聊下么 343290058

**Comment by 727146685** [comment]
发错人了吧？我不知道你在说啥




心情
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MrZhangYuan/AddressParsing"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月27日(星期二) 下午4:17
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [MrZhangYuan/AddressParsing] 带有功能区的地址库和京东地址库同步 (Issue #2)





  
Regions_With_Functional_Area.jso
  
但是这个库里面没有邮政编码，能加个qq私聊下么 343290058

**Comment by heyblues** [comment]
> 某东的地址库
但是这个库里面没有邮政编码，能加个qq私聊下么 343290058

**Comment by MrZhangYuan** [comment]
由于近期较忙，四级地址库暂不支持，有计划支持，谢谢

**Comment by heyblues** [comment]
> 由于近期较忙，四级地址库暂不支持，有计划支持，谢谢

老大，nuget获取的地址不是最新的，我想要一份最新的json，我想更新下dll，感谢

**Comment by heyblues** [comment]
作者您好
现在困扰我问题的没有最新的json 文件，你这个开源库里面的地址不是最新的，我举个例子，比如浙江省嘉兴市 没有南湖区，绍兴市没有柯桥区



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MrZhangYuan/AddressParsing"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月27日(星期二) 下午4:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MrZhangYuan/AddressParsing] 带有功能区的地址库和京东地址库同步 (Issue #2)





 
Closed #2 as completed.

**Comment by MrZhangYuan** [comment]
感谢提醒 我近期更新一下 json是从政府网站收集 自己创建的

**Comment by heyblues** [comment]
> 感谢提醒 我近期更新一下 json是从政府网站收集 自己创建的

老大 方便加个qq？343290058

**Comment by heyblues** [comment]
能否加个qq？343290058，问题有点急



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年2月27日(星期二) 下午4:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MrZhangYuan/AddressParsing] 带有功能区的地址库和京东地址库同步 (Issue #2)





 
某东的地址库

**Comment by PingXD** [comment]
https://github.com/MrZhangYuan/AddressParsing/issues/2#issue-1674274154
你看下顶层的这个log文件  这个里面是我收集的  你看下是否满足你的需求?

**Comment by MrZhangYuan** [comment]
qq:874429156

**Comment by heyblues** [comment]
这几个值没有





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年2月27日(星期二) 下午5:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MrZhangYuan/AddressParsing] 带有功能区的地址库和京东地址库同步 (Issue #2)





 
#2 (comment)
 你看下顶层的这个log文件  这个里面是我收集的  你看下是否满足你的需求?
