### ISSUE TITLE
关于Regions.json

### ISSUE THREAD

**Issue by Monkeywj** [MrZhangYuan/AddressParsing#3]
应用到了地址拆分上，很高效。非常感谢！！
其中有个铜官山区，对应已经变成了铜官区。
所以想请教下，这个json文件可以通过什么方式下载最新的。

**Comment by heyblues** [comment]
> 应用到了地址拆分上，很高效。非常感谢！！ 其中有个铜官山区，对应已经变成了铜官区。 所以想请教下，这个json文件可以通过什么方式下载最新的。
想请教下，后来你后获取到最新的json？

**Comment by MrZhangYuan** [comment]
json是编译到dll里面的，要提交修改
